services:
  backend:
    container_name: template_backend
    image: template_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - database:/app/database
      - logs:/app/logs
    env_file:
      - .env
    command: ["uvicorn", "run:app", "--host", "0.0.0.0", "--port", "${PORT_TEMPLATE_BACK}", "--log-level", "warning"]
    ports:
      - "${PORT_TEMPLATE_BACK}:${PORT_TEMPLATE_BACK}"
    networks:
      - template_network

  frontend:
    container_name: template_frontend
    image: template_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - /var/log/nginx:/var/log/nginx
    ports:
      - "${PORT_TEMPLATE_FRONT}:8081"
    networks:
      - template_network

networks:
  template_network:
    driver: bridge

volumes:
  database:
  logs:
