services:
  backend:
    container_name: ${APP_NAME}_backend
    image: ${APP_NAME}_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - database:/app/database
      - logs:/app/logs
    env_file:
      - .env
    command: ["uvicorn", "run:app", "--host", "0.0.0.0", "--port", "${PORT_BACK}", "--log-level", "warning"]
    ports:
      - "${PORT_BACK}:${PORT_BACK}"
    networks:
      - ${APP_NAME}_network

  frontend:
    container_name: ${APP_NAME}_frontend
    image: ${APP_NAME}_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - VITE_BACKEND_URL="http://backend:${PORT_BACK}"
    env_file:
      - .env
    volumes:
      - /var/log/nginx:/var/log/nginx
    ports:
      - "${PORT_FRONT}:8081"
    networks:
      - ${APP_NAME}_network

networks:
  ${APP_NAME}_network:
    driver: bridge

volumes:
  database:
  logs:
