services:
  auth:
    container_name: ${APP_NAME}_auth
    image: ${APP_NAME}_auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    restart: always
    volumes:
      - auth-database:/app/database
      - auth-logs:/app/logs
    env_file:
      - .env
    command: ["uvicorn", "modules.api.main:app", "--host", "0.0.0.0", "--port", "${PORT_AUTH}", "--log-level", "warning"]
    ports:
      - "${PORT_AUTH}:${PORT_AUTH}"
    networks:
      - app_network

  backend:
    container_name: ${APP_NAME}_backend
    image: ${APP_NAME}_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - backend-logs:/app/logs
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${PORT_BACK}", "--log-level", "warning"]
    ports:
      - "${PORT_BACK}:${PORT_BACK}"
    networks:
      - app_network

  frontend:
    container_name: ${APP_NAME}_frontend
    image: ${APP_NAME}_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_APP_NAME: ${APP_NAME}
        VITE_GITHUB_URL: ${GITHUB_URL}
    restart: always
    environment:
      - VITE_BACKEND_URL="http://backend:${PORT_AUTH}"
      - VITE_APP_NAME="${APP_NAME}"
      - VITE_GITHUB_URL="${GITHUB_URL}"
    env_file:
      - .env
    volumes:
      - /var/log/nginx:/var/log/nginx
    ports:
      - "${PORT_FRONT}:8081"
    networks:
      - app_network

  kuma:
    image: louislam/uptime-kuma:latest
    container_name: kuma
    depends_on:
      - auth
    ports:
      - "3001:3001"
    volumes:
      - ./monitoring/uptime-kuma:/app/data
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  auth-database:
  auth-logs:
  uptime-kuma:
  backend-logs:

