services:
  backend:
    container_name: ground_control_backend
    image: ground_control_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - database:/app/database
      - logs:/app/logs
    env_file:
      - .env
    command: ["uvicorn", "run:app", "--host", "0.0.0.0", "--port", "${PORT_GROUND_CONTROL_BACK}", "--log-level", "warning"]
    ports:
      - "${PORT_GROUND_CONTROL_BACK}:${PORT_GROUND_CONTROL_BACK}"
    networks:
      - ground_control_network

  frontend:
    container_name: ground_control_frontend
    image: ground_control_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - /var/log/nginx:/var/log/nginx
    ports:
      - "${PORT_GROUND_CONTROL_FRONT}:8081"
    networks:
      - ground_control_network

networks:
  ground_control_network:
    driver: bridge

volumes:
  database:
  logs:
