name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Generate build metadata
        working-directory: frontend
        run: |
          HASH=$(git log --grep='^chore(release):' --invert-grep -1 --pretty=format:%h)
          MSG=$(git log --grep='^chore(release):' --invert-grep -1 --pretty=format:%s)
          echo "{\"hash\": \"$HASH\", \"message\": \"$MSG\"}" > build-meta.json
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add build-meta.json
          git commit -m "chore(build): update build metadata [skip ci]" || echo "No changes to commit"
          git push

      - name: Run semantic-release
        working-directory: frontend
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
